### PR TITLE
Compress CUDA binary code

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Did you measure the difference between the two approaches? Would be interested to know how they compare

**Comment by isuruf** [comment]
2GB -> 620 MB

**Comment by carterbox** [comment]
This is unexpected to me since compression is enabled by default, but I guess compression has overhead for small files.

https://docs.nvidia.com/cuda/nvfatbin/index.html#supported-options

**Comment by carterbox** [comment]
@conda-forge-admin, please rerender

**Comment by carterbox** [comment]
I forgot the bot doesn't have permission to build on the CI.

**Comment by carterbox** [comment]
Thanks, @isuruf

**Pull request merged**
